version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - HTTP_PORT=3000
      - AUTH_SERVICE_HOST=auth-service
      - AUTH_SERVICE_PORT=3001
      - ORDERS_SERVICE_HOST=orders-service
      - ORDERS_SERVICE_PORT=3002
    depends_on:
      - auth-service
      - orders-service
    networks:
      - nestjs-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - AUTH_SERVICE_HOST=0.0.0.0
      - AUTH_SERVICE_PORT=3001
    networks:
      - nestjs-network

  orders-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: orders-service
    container_name: orders-service
    ports:
      - "3002:3002"
    environment:
      - ORDERS_SERVICE_HOST=0.0.0.0
      - ORDERS_SERVICE_PORT=3002
    networks:
      - nestjs-network

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: notification-service
    container_name: notification-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    networks:
      - nestjs-network

  # =========================================================
  # Core Persistence Stack (PostgreSQL & Redis)
  # =========================================================
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=workforce_pulse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nestjs-network

  # =========================================================
  # Observability Stack (Metrics & Dashboards & Traces)
  # =========================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - nestjs-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3100:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - nestjs-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # Tempo HTTP
      - "4317:4317" # OTLP gRPC
    networks:
      - nestjs-network

volumes:
  postgres_data:
  redis_data:

networks:
  nestjs-network:
    driver: bridge

