global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'leave-service'
    static_configs:
      - targets: ['host.docker.internal:3003']

  - job_name: 'payroll-service'
    static_configs:
      - targets: ['host.docker.internal:3004']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:3005']
